//Fetch all cryptos types
export const FETCH_CRYPTOS_REQUEST = 'FETCH_CRYPTOS_REQUEST'
export const FETCH_CRYPTOS_SUCCES = 'FETCH_CRYPTOS_SUCCES'
export const FETCH_CRYPTOS_FAILURE = 'FETCH_CRYPTOS_FAILURE'

//Fetch Trending cryptos types
export const FETCH_TRENDING_CRYPTOS_REQUEST = 'FETCH_TRENDING_CRYPTOS_REQUEST'
export const FETCH_TRENDING_CRYPTOS_SUCCES = 'FETCH_TRENDING_CRYPTOS_SUCCES'
export const FETCH_TRENDING_CRYPTOS_FAILURE = 'FETCH_TRENDING_CRYPTOS_FAILURE'